services:
  kafka-service:
    container_name: kafka-service
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  db-service:
    container_name: db-service
    depends_on:
      kafka-service:
        condition: service_healthy
    build: dbservice
    ports:
      - "8081:8081"
    env_file:
      - dbservice/.env
    environment:
      - SERVER_PORT=8081
      - SPRING_KAFKA_URL=kafka-service:9092
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    container_name: user-service
    depends_on:
      kafka-service:
        condition: service_healthy
    build: userservice
    ports:
      - "8082:8082"
    env_file:
      - userservice/.env
    environment:
      - SERVER_PORT=8082
      - SPRING_KAFKA_URL=kafka-service:9092
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8082"]
      interval: 10s
      timeout: 5s
      retries: 5

  wallet-service:
    container_name: wallet-service
    depends_on:
      kafka-service:
        condition: service_healthy
    build: walletservice
    ports:
      - "8084:8084"
    env_file:
      - walletservice/.env
    environment:
      - SERVER_PORT=8084
      - SPRING_KAFKA_URL=kafka-service:9092
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8084"]
      interval: 10s
      timeout: 5s
      retries: 5
